### ISSUE TITLE
关于更新的疑惑

### ISSUE THREAD

**Issue by Neomanbeta** [mixool/kuhero#18]
最近的两次更新，我都需要删除dyno然后重新部署才能用，这是正确的操作么？不是自动更新的？

**Comment by mixool** [comment]
我这边更新应该不影响你已经部署的app吧

**Comment by Neomanbeta** [comment]
但是两次都是不能用了（很早之前部署的一直都好用），我来这里才发现你更新了，删掉重新部署就能用了，第二天发现又不能用的时候，上来发现你又更新了，然后我再操作一次（删掉以后重新部署），才可以继续用，所以才有疑惑想问一下不能用是因为你这里更新的原因么？

**Comment by mixool** [comment]
> 但是两次都是不能用了（很早之前部署的一直都好用），我来这里才发现你更新了，删掉重新部署就能用了，第二天发现又不能用的时候，上来发现你又更新了，然后我再操作一次（删掉以后重新部署），才可以继续用，所以才有疑惑想问一下不能用是因为你这里更新的原因么？

除非app休眠后 heroku会重新拉取代码部署，应该不是这个机制
不过我也不确定，待更多反馈

**Comment by mixool** [comment]
> 但是两次都是不能用了（很早之前部署的一直都好用），我来这里才发现你更新了，删掉重新部署就能用了，第二天发现又不能用的时候，上来发现你又更新了，然后我再操作一次（删掉以后重新部署），才可以继续用，所以才有疑惑想问一下不能用是因为你这里更新的原因么？

想了一下！ ！！！休眠后启动，会重新执行run.sh ，因为我更新时候也更新了配置文件 所以导致你不能用！！！

避免这种问题你可以抄写一份caddyfile和v2ray配置文件放到gist，再使用自定义配置网络地址参数启动。

另外v2ray不更新新功能，我近期不会有啥更新了，期待v2ray 5.0的到来..

**Comment by Neomanbeta** [comment]
多谢解答，明白了。
